import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useNotifications } from '@/hooks/use-notifications'
import type { UserProfileRecord } from '@/../../shared/contracts'

const branches = ['Goa', 'Tinambac', 'Tigaon', 'Lagonoy'] as const
type ProfileForm = { displayName: string; username: string; password: string; role: 'ADMIN' | 'CASHIER'; branch: (typeof branches)[number]; isActive: boolean }
const blank: ProfileForm = { displayName: '', username: '', password: '', role: 'CASHIER', branch: 'Goa', isActive: true }
export function UserProfilesSettings(): React.JSX.Element {
  const [profiles, setProfiles] = React.useState<UserProfileRecord[]>([]); const [form, setForm] = React.useState<ProfileForm>(blank); const [selected, setSelected] = React.useState<UserProfileRecord>(); const { notify } = useNotifications()
  const load = React.useCallback(async () => { try { setProfiles(await window.api.userProfiles.list()) } catch { notify({ type: 'error', title: 'User profiles could not be loaded.' }) } }, [notify])
  React.useEffect(() => { void load() }, [load])
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { if (selected) await window.api.userProfiles.update({ id: selected.id, displayName: form.displayName, username: form.username, role: form.role, branch: form.branch, isActive: form.isActive }); else await window.api.userProfiles.create(form); setSelected(undefined); setForm(blank); await load(); notify({ type: 'success', title: 'User profile saved.' }) } catch { notify({ type: 'error', title: 'User profile could not be saved.' }) } }
  const reset = async (profile: UserProfileRecord) => { const password = window.prompt(`Temporary password for ${profile.displayName}`); if (!password) return; try { await window.api.userProfiles.resetPassword({ id: profile.id, password }); notify({ type: 'success', title: 'Temporary password issued.' }) } catch { notify({ type: 'error', title: 'Password could not be reset.' }) } }
  return <section className="mt-6 flex max-w-3xl flex-col gap-4"><div><p className="text-sm font-medium">User Profiles</p><p className="text-xs text-muted-foreground">Create, manage, and deactivate staff accounts.</p></div><div className="max-h-48 overflow-y-auto rounded-md border"><table className="w-full text-sm"><tbody>{profiles.map((profile) => <tr key={profile.id} className="border-b last:border-0"><td className="p-2"><div>{profile.displayName}</div><div className="text-xs text-muted-foreground">{profile.username} · {profile.role} · {profile.branch}</div></td><td className="p-2 text-right"><Button size="sm" variant="ghost" onClick={() => { setSelected(profile); setForm({ displayName: profile.displayName, username: profile.username, password: '', role: profile.role, branch: profile.branch, isActive: profile.isActive }) }}>Edit</Button><Button size="sm" variant="ghost" onClick={() => void reset(profile)}>Reset password</Button></td></tr>)}</tbody></table></div><form onSubmit={(event) => void save(event)}><FieldGroup><Field><FieldLabel>Display name</FieldLabel><Input value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} required /></Field><Field><FieldLabel>Username</FieldLabel><Input value={form.username} disabled={Boolean(selected)} onChange={(event) => setForm({ ...form, username: event.target.value })} required /></Field>{!selected && <Field><FieldLabel>Temporary password</FieldLabel><Input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /></Field>}<Field><FieldLabel>Role</FieldLabel><Select value={form.role} onValueChange={(role) => setForm({ ...form, role: role as 'ADMIN' | 'CASHIER' })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="CASHIER">Cashier</SelectItem><SelectItem value="ADMIN">Admin</SelectItem></SelectContent></Select></Field><Field><FieldLabel>Branch</FieldLabel><Select value={form.branch} onValueChange={(branch) => setForm({ ...form, branch: branch as ProfileForm['branch'] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{branches.map((branch) => <SelectItem key={branch} value={branch}>{branch}</SelectItem>)}</SelectContent></Select></Field><Button type="submit">{selected ? 'Update profile' : 'Create profile'}</Button>{selected && <Button type="button" variant="outline" onClick={() => { setSelected(undefined); setForm(blank) }}>Cancel</Button>}</FieldGroup></form></section>
}
