import { useState, type FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Field, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { useNotifications } from '@/hooks/use-notifications'
import type { AuthenticatedUser } from '@/../../shared/contracts'

export function InitialAdminSetup({ onSuccess }: { onSuccess: (user: AuthenticatedUser) => void }): React.JSX.Element {
  const [displayName, setDisplayName] = useState(''); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string>(); const [isSubmitting, setIsSubmitting] = useState(false); const { notify } = useNotifications()
  const submit = async (event: FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); if (password !== confirmation) { setError('Passwords do not match.'); return }; setIsSubmitting(true); setError(undefined); try { onSuccess(await window.api.auth.setupInitialAdmin({ displayName, username, password })); notify({ type: 'success', title: 'Administrator account created.' }) } catch { setError('The administrator account could not be created.'); notify({ type: 'error', title: 'Setup failed.' }) } finally { setIsSubmitting(false) } }
  return <form className="flex w-full max-w-sm flex-col gap-6" onSubmit={(event) => void submit(event)}><div className="flex flex-col gap-1"><h1 className="text-xl font-semibold tracking-tight">Set up your workspace</h1><p className="text-sm text-muted-foreground">Create the first administrator account to begin.</p></div><FieldGroup><Field><FieldLabel htmlFor="setup-name">Display name</FieldLabel><Input id="setup-name" value={displayName} onChange={(event) => setDisplayName(event.target.value)} required /></Field><Field><FieldLabel htmlFor="setup-username">Username</FieldLabel><Input id="setup-username" value={username} onChange={(event) => setUsername(event.target.value)} minLength={3} required /></Field><Field><FieldLabel htmlFor="setup-password">Password</FieldLabel><Input id="setup-password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={8} required /></Field><Field><FieldLabel htmlFor="setup-confirmation">Confirm password</FieldLabel><Input id="setup-confirmation" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} minLength={8} required /></Field><Button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Creating…' : 'Create administrator account'}</Button>{error && <FieldError>{error}</FieldError>}</FieldGroup></form>
}
